# -*- coding: utf-8 -*-
"""Web scrapping Indeed with BeautifulSoup

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/gist/khuyentran1401/095f264daf57f5676322e22815fa5bb6/web-scrapping-indeed-with-beautifulsoup.ipynb

In this project, I am interested in extracting the data relevant to my internship search such as title, location, company, and the link to apply. 

I used Beautiful Soup, a libary of Python to scrap web easily without strong knowledge in HTML
"""

import requests
from bs4 import BeautifulSoup

URL = 'https://www.indeed.com/jobs?q=data+science+intern&l=San+Jose%2C+CA#'
page = requests.get(URL)

soup = BeautifulSoup(page.content, 'html.parser')

results = soup.find(id='resultsCol')

"""Find the job listings"""

job_elems = results.find_all('div',class_="jobsearch-SerpJobCard unifiedRow row result")

"""Extract the non-relevant data to make the results easier to see"""

for job_elem in job_elems:

  title = job_elem.find('div', class_ = 'title')
  company = job_elem.find('span', class_='company')
  location = job_elem.find('span', class_ = "location accessible-contrast-color-location" )
  link = job_elem.find('a')['href']
  summary = job_elem.find('div', class_ = 'summary')
  print(title.text.strip())
  print(company.text.strip())
  print(location.text.strip())
  print()
  print("Apply here:", link)
  print()